name: deploy_frontend
# deploys on push from frontend folder

on:
    push:
        branches: [ main ]
        paths: 
        - 'frontend/**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name azresumemcdonald --auth-mode key -d '$web' -s frontend/
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "AzureResumeCDN-McDonald" --name "AzureResumeCDN-McDonald" --resource-group "AzureResume-rg"

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
